### ISSUE TITLE
ConfigureKestrel not working locally, how to setup AAD app registration for daemon apps

### ISSUE THREAD

**Issue by Markz878** [damienbod/GrpcAzureAppServiceAppAuth#1]
Is this possible to get working locally? If I run the app after creating Azure App Registration and changing appsettings, I get this error:
```
Grpc.Core.RpcException: 'Status(StatusCode="Unavailable", Detail="Error starting gRPC call. HttpRequestException: The SSL connection could not be established, see inner exception. IOException: Cannot determine the frame size or a corrupted frame was received.", DebugException="System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Cannot determine the frame size or a corrupted frame was received.
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
```

And if comment out the Kestrel configuration in Service Program.cs (lines 31-38) I get this error:
`Grpc.Core.RpcException: 'Status(StatusCode="Unauthenticated", Detail="Bad gRPC response. HTTP status code: 401")'`

Also, could you tell the steps you did while creating the Azure App Registration? It is enough to just create the app registration and create the client secret?

**Comment by damienbod** [comment]
Hi @Markz878 

I needed to add this for local dev:

```
listenOptions.UseHttps(); // required for local debugging, not for the Azure deployment
```
This should work locally now. 

The app registration needs to be created with a secret/certificate and the scope

```
"Scope": "api://--your-client-id--/.default"
```

**Comment by Markz878** [comment]
Thanks for the response. 
Unfortunately the Unauthenticated error still persists.. 
If I remove the Authorize-attribute, the code enters the SayHello method, and I can see that ServerCallContext context variable contains in RequestHeaders my authorization header with correct and valid jwt. I guess it's not a problem that it's in lowercase as in 'authorization'? 

My Service project also logs that  "Security token validated". But if I try to convert the ServerCallContext  to "var user = context.GetHttpContext().User", the user does not have any claims... Looks like Asp.Net can't bind the ClaimsPrincipal.. Any idea what could be the problem? I even removed all code inside AddAuthorization method and removed the policy from Authorize-attribute, but it did not help.

And I can't create an App Registration scope with name .default in Azure Portal, the dot at the start is not allowed, is that naming possible through cli or how did you do it?

**Comment by Markz878** [comment]
@damienbod Can you please help me? How did you setup App registration, I assume single tenant? Did you have to add redirect uri? Do you need access or id tokens?

And as a sidenote, as you probably know, ASP.Net Core auth story is often criticized as being too cumbersome. You could help this a lot by adding more steps to your tutorials, especially in Azure side, this is like the third tutorial from you that I try to follow where I have to try things out a lot since you haven't added the necessary steps to make it work straight away, thank you.

**Comment by damienbod** [comment]
@Markz878 If the name claim has no value, then you need to define this in the parameters. You might need to reset the default claim mappings or add this as defined. ASP.NET Core middleware added namespaces per default to certain claims. 

I didn't add any Azure App registration docs to the blog, repo, that would help. See the **Microsoft.Identity.Client** docs for the App registration setup. You use a application client (no user) 

In the App registration | Expose an API the Application ID URI need to be active without the default. Then you can use the default as like the demo. You don't use consent then. This is because this is an application client and no a user client.

Greetings Damien

**Comment by Markz878** [comment]
@damienbod Sorry but I don't understand any of this advice.. I have cloned your repo and replaced the appsettings parameters in Service for AzureAd: { Domain, TenantId, ClientId and ClientSecret }, and in Client AzureADServiceApi: {ClientId, Authority, Scope}. Shouldn't this just work after that? Comment for each paragraph:

1: I don't have a name claim in my jwt. What does that mean "then you need to define this in the parameters", what parameters? In code? Or in Azure? And what about "need to reset the default claim mappings or add this as defined"? I went to Azure portal, and in my app registration in Token configuration added email, family_name and given_name claims, but it did not help.

2. What do you mean by this "you use a application client (no user)"? So in App registration in Authentication there is Platform configurations. Are you saying that I need to use Mobile and desktop applications? But the Grpc Service is a web app right? Or what do you actually mean by this?

3. Yes in Expose an API the Application ID URI is set, and I can use the .default scope, or at least the Service project logs  that token is valid when I pass it to my Service.

**Comment by damienbod** [comment]
@Markz878 It is hard to know how much I need to write docs for. Every IDP does this different and setting a client for each OIDC server is still different. Azure AD and Azure AD B2C have a few specifics.

Maybe I would understand better with some more details:

You want to run the local console application using the local API, correct?

1. Does the console application get the application back from the AAD identity provider?
2. Can you look at the token and see what is in it? jwt.ms (if you have the wrong token, maybe you need to validate that you use a V2 endpoint and request a role access_as_application, guessing her.)
3. Can you remove the authorize attribute in the GRPC service and see it if works?
4. If this works, add a breakpoint in the GRPC service and see what claims you have?
5. What is the value of the name claim?

Greetings Damien

**Comment by Markz878** [comment]
@damienbod Yes, I would like to test everything locally first.
1. Yes, the authResult has a value with AccessToken populated.
2. Here are my jwt claims with some info redacted: 
{
  "typ": "JWT",
  "alg": "RS256",
  "x5t": "2ZQpJ3UpbjAYXYGaXEJl8lV0TOI",
  "kid": "2ZQpJ3UpbjAYXYGaXEJl8lV0TOI"
}.{
  "aud": "api://XXXXXXXX-XXXX-XXXX-XXXX-997f8950ce08",
  "iss": "https://sts.windows.net/XXXXXXXX-f409-XXXX-XXXX-76ce62c20e4d/",
  "iat": 1662112842,
  "nbf": 1662112842,
  "exp": 1662116742,
  "aio": "E2ZgYAjfzNLTeOdoLqvgx79rWR+kAwA=",
  "appid": "XXXXXXXX-XXXX-XXXX-XXXX-997f8950ce08",
  "appidacr": "1",
  "idp": "https://sts.windows.net/XXXXXXXX-XXXX-XXXX-XXXX-76ce62c20e4d/",
  "oid": "",
  "rh": "0.AV8AoPQkBAn0hUGdnXbOYsIOTRoGWGmfJYBFvRuZf4lQzghfAAA.",
  "sub": "",
  "tid": "",
  "uti": "HFjyPaT4m0u_CfhYY0MeAA",
  "ver": "1.0"
}.[Signature]
3. Yes I did that and it works.
4. Like I said earlier, when I remove Authorize attribute, and try to get ClaimsPrincipal from ServerCallContext using context.GetHttpContext().User, the ClaimsPrincipal does not have any claims. ASP.Net Core doesn't seem to bind them from the Authorization header.
5. There is no name claim.

Thanks for the help!

**Comment by damienbod** [comment]
Hi  @Markz878 The access token should be "ver": "2.0", you can update this in the Azure App registration manifest.

I will run locally and compare

**Comment by damienbod** [comment]
Otherwise it looks good. You would need to remove this as well or update it to match your token once you switch to a V2 token

https://github.com/damienbod/GrpcAzureAppServiceAppAuth/blob/main/GrpcAzureAppServiceAppAuth/Program.cs#L17

**Comment by Markz878** [comment]
@damienbod I set accessTokenAcceptedVersion to 2 in the manifest and removed that line 17 from Program.cs, and now my jwt looks like this:
{
  "typ": "JWT",
  "alg": "RS256",
  "kid": "2ZQpJ3UpbjAYXYGaXEJl8lV0TOI"
}.{
  "aud": "XXXXXXXX-XXXX-XXXX-XXXX-997f8950ce08",
  "iss": "https://login.microsoftonline.com/XXXXXXXX-XXXX-XXXX-XXXX-76ce62c20e4d/v2.0",
  "iat": 1662119040,
  "nbf": 1662119040,
  "exp": 1662122940,
  "aio": "E2ZgYPg260Zwie2f9JS3IbNs2/tmAAA=",
  "azp": "XXXXXXXX-XXXX-XXXX-XXXX-997f8950ce08",
  "azpacr": "1",
  "oid": "XXXXXXXX-XXXX-XXXX-XXXX-34a7c4bc94e9",
  "rh": "0.AV8AoPQkBAn0hUGdnXbOYsIOTRoGWGmfJYBFvRuZf4lQzghfAAA.",
  "sub": "XXXXXXXX-XXXX-XXXX-XXXX-34a7c4bc94e9",
  "tid": "XXXXXXXX-XXXX-XXXX-XXXX-76ce62c20e4d",
  "uti": "1wE1nb0qSEKQtfzrv3FpAA",
  "ver": "2.0"
}.[Signature]
And I'm still getting the same Unauthenticated error in Client, while my Service project logs that "IDX10241: Security token validated."

I have tried to configure Azure App Registration by setting Platform configurations to Web server with redirect uri https://localhost:7179/signin-oidc, and Mobile and desktop apps with redirect uri http://localhost. I tried adding every single optional claim in Token configuration page. I tried adding a custom scope access_as_user (was not allowed, client says that for client app it has to be .default scope..). None of this works... I ofc removed those changes from app registration after each try.

I have cloned your code, set the appsettings to my App registration values, applied your previous comment's changes.  Are you saying that this all works for you locally? Your blog post specifically targets Azure Ad, so I would hope that this should work by following your instructions.

**Comment by damienbod** [comment]
@Markz878  yes this works locally for me and also in all my Azure AD deployments, I use this in a lot of different clients. You access token looks fine. I usually add an **access_as_application** scope and use this as a role in my Azure App registration.  

The Azure App Registration does not need any redirectURL, it is just an API definition.

Does it work with just the [Authorize] on the GRPC service?

**Comment by damienbod** [comment]
Some MS docs:

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki

https://github.com/AzureAD/microsoft-identity-web/wiki/web-apis

only **access_as_application** in your use case.

**Comment by Markz878** [comment]
> Does it work with just the [Authorize] on the GRPC service?

No, unfortunately it does not work with just a plain [Authorize] attribute.

**Comment by damienbod** [comment]
You need to turn on the debug logs (PII as well) on the API an see the reason why the access token is rejected.

**Comment by Markz878** [comment]
I have turned PII on several times by now, and with Default logging level as Debug the logs look like this (PII off for privacy reasons but they just show the token):

warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Overriding address(es) 'https://localhost:7179'. Binding to endpoints defined via IConfiguration and/or UseKestrel() instead.
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:8080
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://[::]:7179
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\user\Downloads\GrpcAzureAppServiceAppAuth-main\GrpcAzureAppServiceAppAuth-main\GrpcAzureAppServiceAppAuth\
crit: Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter[0]
      Microsoft.IdentityModel Version: 6.20.0.0. Date 09/02/2022 16:28:35. PII logging is OFF. See https://aka.ms/IdentityModel/PII for details.
info: Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter[0]
      IDX10242: Security token: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]' has a valid signature.
info: Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter[0]
      IDX10239: Lifetime of the token is valid.
info: Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter[0]
      IDX10234: Audience Validated.Audience: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'
info: Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter[0]
      IDX10246: ValidateTokenReplay property on ValidationParameters is set to false. Exiting without validating the token replay.
info: Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter[0]
      IDX10237: ValidateIssuerSigningKey property on ValidationParameters is set to false. Exiting without validating the issuer signing key.
info: Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter[0]
      IDX10255: TypeValidator property on ValidationParameters is null and ValidTypes is either null or empty. Exiting without validating the token type.
info: Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter[0]
      IDX10245: Creating claims identity from the validated token: '[PII of type 'System.IdentityModel.Tokens.Jwt.JwtSecurityToken' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
info: Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter[0]
      IDX10241: Security token validated. token: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.

**Comment by Markz878** [comment]
@damienbod Could you update your blog and show how this should work step by step by cloning your code and creating a new app registration in Azure?
There is really no point in making tutorials where half of the steps are omitted.. If it's easy and obvious, why create tutorials for it? And if it's not, why skip half of the steps?

**Comment by damienbod** [comment]
I have a blog here which does almost the same:

https://damienbod.com/2020/10/01/implement-azure-ad-client-credentials-flow-using-client-certificates-for-service-apis/

@Markz878 Microsoft have documented this as well. The App registration looks good now I guess, something inside you API does not, guess some incorrect GUID etc Maybe if you enabled the PII logs, you might see the reason. The logs above have is disabled. I cannot see what is incorrect on your AAD and client from the information you provide. 

A guess is that you need at least one role in the token. 

Try to follow these Microsoft docs for setting up a confidential client without a user.

https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-daemon-overview

PS I will add the Azure App registration steps to the blog as well and create a new Web API application to validate.

Greetings Damien

**Comment by damienbod** [comment]
And here's the exact example from Microsoft with the App registration and API setup

https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/tree/master/2-Call-OwnApi

**Comment by damienbod** [comment]
@Markz878 

Tested this and was able to reproduce. The API gives bad error logs just like you reported. The Microsoft.Identity logs could be improved.

The problem is that you need to add a role and expose this for the API to work.

I added a step by step in images from 1-5 for you to set this up.

https://github.com/damienbod/GrpcAzureAppServiceAppAuth/tree/main/images

Once the roles claims is included in your V2 access token and you have grant consent in the App registration, it will work.

Please try

Greetings Damien

**Comment by Markz878** [comment]
Hallelujah, it works. Faith in humanity/Azure/Microsoft restored :)
Thanks a lot @damienbod
